# Help Command Center Configuration

# This file contains the configuration settings for the Help Command Center application.
# You can modify these settings to customize the behavior of the application.
# General settings
general:
  app_name: "Help Command Center"
  version: "1.0.0"

# Display settings
display:
  colors: true
  max_width: 80
  show_timestamps: true

# Search settings
search:
  max_results: 10
  case_sensitive: false
  search_history_size: 100

# Logging settings
logging:
  level: info  # debug, info, warning, error
  file: logs/helpcc.log
  max_size: 10MB
  max_files: 5

# Cache settings
cache:
  enabled: true
  directory: .cache/helpcc
  max_size: 100MB
  ttl: 3600  # Time to live in seconds

# Command aliases
aliases:
  help: "h"
  search: "s"
  quit: "q"
  clear: "c" 